server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept
  prefix: /facemash #给路由增加前缀
  ignored-services: "*"  #原真实服务名称全部忽略
  routes:
    mydept.serviceId: SPRINGCLOUD-DEPT #真实服务名称
    mydept.path: /mydept/**   #路由地址

info:
  app.name: facemash-microservicecloud
  company.name: facemash.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$


